const copy = {
  appName: 'دفتر حساب سیمرغ',
  shortName: 'سیمرغ',
  tagline: 'حساب‌وکتاب ساده با دوستان و آشنایان',
  comingSoon: 'به‌زودی اینجا فهرست اشخاص را می‌بینید.',
  signIn: {
    title: 'ورود به سیمرغ',
    emailLabel: 'ایمیل',
    sendCode: 'ارسال کد ورود',
    sending: 'در حال ارسال…',
    firstTimeNote: 'اگر نخستین بار است که وارد می‌شوید، حسابتان به‌طور خودکار ساخته می‌شود.',
    codeTitle: 'کد ۶ رقمی را وارد کنید',
    codeSentTo: 'کد به این ایمیل فرستاده شد:',
    changeEmail: 'تغییر ایمیل',
    verify: 'ورود',
    verifying: 'در حال بررسی…',
    resendIn: 'ارسال دوباره تا',
    resendSeconds: 'ثانیه دیگر',
    resend: 'ارسال دوباره کد',
    errInvalidEmail: 'این ایمیل درست نیست. آن را بررسی کنید.',
    errRateLimited: 'تعداد درخواست‌ها زیاد بوده است. کمی بعد دوباره امتحان کنید.',
    errWaitSeconds: 'لطفاً چند ثانیه صبر کنید و دوباره امتحان کنید.',
    errEmailFailed: 'ارسال ایمیل ناموفق بود. کمی بعد دوباره امتحان کنید.',
    errNetwork: 'اتصال برقرار نیست. دوباره امتحان کنید.',
    errWrongCode: 'کد اشتباه است.',
    errAttemptsLeft: 'فرصت‌های باقی‌مانده:',
    errCodeExpired: 'کد منقضی شده است. یک کد تازه بگیرید.',
    errInvalidCode: 'کد باید ۶ رقم باشد.',
    errGeneric: 'مشکلی پیش آمد. دوباره امتحان کنید.',
    digitLabel: 'رقم',
  },
  settings: {
    title: 'تنظیمات',
    account: 'حساب کاربری',
    logout: 'خروج از حساب',
    back: 'بازگشت',
    errLogout: 'خروج انجام نشد. اتصال را بررسی کنید و دوباره امتحان کنید.',
    version: 'دفتر حساب سیمرغ · نسخه‌ی ۱',
  },
  loading: 'در حال بارگذاری…',
} as const

export default copy
