const copy = {
  appName: 'دفتر حساب سیمرغ',
  shortName: 'سیمرغ',
  tagline: 'حساب‌وکتاب ساده با دوستان و آشنایان',
  comingSoon: 'به‌زودی اینجا فهرست اشخاص را می‌بینید.',
  signIn: {
    title: 'ورود به سیمرغ',
    emailLabel: 'ایمیل',
    sendCode: 'ارسال کد ورود',
    sending: 'در حال ارسال…',
    firstTimeNote: 'اگر نخستین بار است که وارد می‌شوید، حسابتان به‌طور خودکار ساخته می‌شود.',
    codeTitle: 'کد ۶ رقمی را وارد کنید',
    codeSentTo: 'کد به این ایمیل فرستاده شد:',
    changeEmail: 'تغییر ایمیل',
    verify: 'ورود',
    verifying: 'در حال بررسی…',
    resendIn: 'ارسال دوباره تا',
    resendSeconds: 'ثانیه دیگر',
    resend: 'ارسال دوباره کد',
    errInvalidEmail: 'این ایمیل درست نیست. آن را بررسی کنید.',
    errRateLimited: 'تعداد درخواست‌ها زیاد بوده است. کمی بعد دوباره امتحان کنید.',
    errWaitSeconds: 'لطفاً چند ثانیه صبر کنید و دوباره امتحان کنید.',
    errEmailFailed: 'ارسال ایمیل ناموفق بود. کمی بعد دوباره امتحان کنید.',
    errNetwork: 'اتصال برقرار نیست. دوباره امتحان کنید.',
    errWrongCode: 'کد اشتباه است.',
    errAttemptsLeft: 'فرصت‌های باقی‌مانده:',
    errCodeExpired: 'کد منقضی شده است. یک کد تازه بگیرید.',
    errInvalidCode: 'کد باید ۶ رقم باشد.',
    errGeneric: 'مشکلی پیش آمد. دوباره امتحان کنید.',
    digitLabel: 'رقم',
  },
  settings: {
    title: 'تنظیمات',
    account: 'حساب کاربری',
    logout: 'خروج از حساب',
    back: 'بازگشت',
    errLogout: 'خروج انجام نشد. اتصال را بررسی کنید و دوباره امتحان کنید.',
    version: 'دفتر حساب سیمرغ · نسخه‌ی ۱',
  },
  loading: 'در حال بارگذاری…',
  common: { back: 'بازگشت', close: 'بستن', retry: 'تلاش دوباره', toman: 'تومان' },
  home: {
    totalOwedToMe: 'طلب من',
    totalIOwe: 'بدهی من',
    addPerson: '+ شخص جدید',
    openSettings: 'تنظیمات',
    owedSuffix: 'طلب',
    oweSuffix: 'بدهی',
    settled: 'تسویه',
    emptyTitle: 'هنوز کسی را اضافه نکرده‌اید.',
    emptyHint: 'با «شخص جدید» شروع کنید.',
    loadError: 'بارگذاری ناموفق بود.',
  },
  person: {
    menu: 'منو',
    rename: 'تغییر نام',
    deletePerson: 'حذف شخص',
    deleteConfirm: 'برای حذف دوباره بزنید',
    deleteWarnAnd: 'و',
    deleteWarnTail: 'تراکنش او حذف می‌شود.',
    deleteWarnNone: 'این شخص حذف می‌شود.',
    owedToMe: 'از او طلب دارم',
    iOwe: 'به او بدهکارم',
    settled: 'تسویه',
    paidButton: 'پرداخت کردم',
    receivedButton: 'دریافت کردم',
    paid: 'پرداخت',
    received: 'دریافت',
    noTransactions: 'هنوز تراکنشی ثبت نشده است.',
    notFound: 'این شخص پیدا نشد. شاید حذف شده باشد.',
    backHome: 'بازگشت به خانه',
  },
  personSheet: {
    addTitle: 'شخص جدید',
    renameTitle: 'تغییر نام',
    nameLabel: 'نام',
    add: 'افزودن',
    save: 'ذخیره',
  },
  txSheet: {
    addTitle: 'تراکنش با',
    editTitle: 'ویرایش تراکنش',
    amountLabel: 'مبلغ (تومان)',
    dateLabel: 'تاریخ',
    today: 'امروز',
    yesterday: 'دیروز',
    pickDate: 'انتخاب تاریخ',
    noteLabel: 'توضیح (اختیاری)',
    notePlaceholder: 'مثلاً قرض برای ماشین',
    save: 'ذخیره',
    saveChanges: 'ذخیره‌ی تغییرات',
    deleteTx: 'حذف تراکنش',
    deleteConfirm: 'برای حذف دوباره بزنید',
    saving: 'در حال ذخیره…',
  },
  calendar: { title: 'تقویم', prevMonth: 'ماه قبل', nextMonth: 'ماه بعد', today: 'امروز' },
  toast: { saved: 'ذخیره شد', deleted: 'حذف شد' },
  errors: {
    network: 'اتصال برقرار نیست. دوباره امتحان کنید.',
    invalid_name: 'نام باید بین ۱ تا ۶۰ نویسه باشد.',
    invalid_amount: 'مبلغ باید عددی صحیح، بیشتر از صفر و حداکثر ۱٬۰۰۰ میلیارد تومان باشد.',
    invalid_date: 'تاریخ درست نیست.',
    invalid_note: 'توضیح نباید بیشتر از ۲۰۰ نویسه باشد.',
    invalid_direction: 'نوع تراکنش درست نیست.',
    invalid_body: 'اطلاعات ارسالی درست نیست.',
    not_found: 'این مورد پیدا نشد. شاید پیش‌تر حذف شده باشد.',
    internal: 'مشکلی پیش آمد. دوباره امتحان کنید.',
  },
} as const

export default copy
